name: dartian_http
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '^3.9.4'

dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  dart_jsonwebtoken: ^3.3.1
  crypto: ^3.0.6
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.16.0
  http: ^0.13.3

resolution: workspace
