name: dartian_http
description: Dartian HTTP kernel
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.4

dependencies:
  shelf: ^1.4.1
  crypto: ^3.0.0
  dartian_i18n:
    path: ../dartian_i18n
  dartian_core:
    path: ../dartian_core

dev_dependencies:
  test: ^1.24.0
