name: dartian_orm
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.4

# Add regular dependencies here.
dependencies:
  drift: ^2.0.0
  sqlite3: ^2.0.0
  path: any
  faker: ^2.0.0

dev_dependencies:
  drift_dev: ^2.0.0
  build_runner: any
  lints: ^6.0.0
  test: ^1.25.6
resolution: workspace
