name: dartian
description: Dartian Monorepo
version: 0.0.1
publish_to: none

environment:
  sdk: '^3.9.4'

dependencies:
  dartian_cli:
    path: packages/dartian_cli
  dartian_core:
    path: packages/dartian_core
  dartian_di:
    path: packages/dartian_di
  dartian_http:
    path: packages/dartian_http
  dartian_i18n:
    path: packages/dartian_i18n
  dartian_orm:
    path: packages/dartian_orm
  dartian_queue:
    path: packages/dartian_queue
  dartian_redis:
    path: packages/dartian_redis
  dartian_router:
    path: packages/dartian_router
  dartian_scheduler:
    path: packages/dartian_scheduler
  dartian_view:
    path: packages/dartian_view
  dartian_events:
    path: packages/dartian_events
  dartian_validation:
    path: packages/dartian_validation

workspace:
  - packages/dartian_cli
  - packages/dartian_core
  - packages/dartian_di
  - packages/dartian_http
  - packages/dartian_i18n
  - packages/dartian_orm
  - packages/dartian_queue
  - packages/dartian_redis
  - packages/dartian_router
  - packages/dartian_scheduler
  - packages/dartian_view
  - packages/dartian_events
  - packages/dartian_validation
